Enhancement UI for Add and Delete list items
digi-serve/test_pwa pull request #5
Opened 2023-08-01 10:17 UTC by guyyoo

https://github.com/digi-serve/test_pwa/issues/1

2023-08-02 07:19 UTC, nh758 approved these changes

2023-08-03 01:42 UTC, Hiro-Nakamura requested changes
Looks good.  Just update the `core` to the latest `#importOnly` branch and then change the `dataInitialized` to `isDataInitialized`

Then good to go!

2023-08-03 01:42 UTC, Hiro-Nakamura commented on src/js/routes.js
> +                     if (dc && !dc.dataInitialized) {
Heads Up:  I'm changing `.dataInitialized`  too `.isDataInitialized`

2023-08-03 06:35 UTC, guyyoo commented
> Looks good. Just update the `core` to the latest `#importOnly` branch and then change the `dataInitialized` to `isDataInitialized`
> 
> Then good to go!

Thanks!

2023-08-03 06:38 UTC, merged